nelmio_api_doc:
    documentation:
        info:
            title: Task Manager API
            description: API for managing users and tasks
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
            host_patterns: []